-- MySQL Script generated by MySQL Workbench
-- Sat Feb  2 14:37:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema codijob
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codijob
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codijob` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `codijob` ;

-- -----------------------------------------------------
-- Table `codijob`.`t_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codijob`.`t_proyecto` (
  `pro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_nom` VARCHAR(45) NULL,
  `pro_desc` VARCHAR(45) NULL,
  `pro_fecha` DATE NULL,
  `pro_url` VARCHAR(45) NULL,
  PRIMARY KEY (`pro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codijob`.`t_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codijob`.`t_usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nom` TEXT NULL,
  `usu_ape` TEXT NULL,
  `usu_email` VARCHAR(45) NULL,
  `usu_hash` TEXT NULL,
  `usu_salt` TEXT NULL,
  `usu_tip` VARCHAR(45) NULL,
  `usu_web` TEXT NULL,
  `usu_git` TEXT NULL,
  `usu_ima` TEXT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codijob`.`t_usuarioproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codijob`.`t_usuarioproyecto` (
  `usupro_id` INT NOT NULL AUTO_INCREMENT,
  `pro_id` INT NULL,
  `usu_id` INT NULL,
  PRIMARY KEY (`usupro_id`),
  INDEX `fk_t_usuarioproyecto_t_proyecto_idx` (`pro_id` ASC),
  INDEX `fk_t_usuarioproyecto_t_usuario1_idx` (`usu_id` ASC),
  CONSTRAINT `fk_t_usuarioproyecto_t_proyecto`
    FOREIGN KEY (`pro_id`)
    REFERENCES `codijob`.`t_proyecto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_usuarioproyecto_t_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `codijob`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codijob`.`t_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codijob`.`t_grupo` (
  `grupo_id` INT NOT NULL AUTO_INCREMENT,
  `grupo_nom` VARCHAR(45) NULL,
  `grupo_foto` VARCHAR(45) NULL,
  `grupo_prom` VARCHAR(45) NULL,
  PRIMARY KEY (`grupo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codijob`.`t_usuariogrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codijob`.`t_usuariogrupo` (
  `usugrupo_id` INT NOT NULL AUTO_INCREMENT,
  `grupo_id` INT NULL,
  `usu_id` INT NULL,
  PRIMARY KEY (`usugrupo_id`),
  INDEX `fk_t_usuariogrupo_t_usuario1_idx` (`usu_id` ASC),
  INDEX `fk_t_usuariogrupo_t_grupo1_idx` (`grupo_id` ASC),
  CONSTRAINT `fk_t_usuariogrupo_t_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `codijob`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_usuariogrupo_t_grupo1`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `codijob`.`t_grupo` (`grupo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codijob`.`t_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codijob`.`t_skill` (
  `skill_id` INT NOT NULL AUTO_INCREMENT,
  `skill_nom` VARCHAR(45) NULL,
  PRIMARY KEY (`skill_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codijob`.`t_ususkill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codijob`.`t_ususkill` (
  `ususkill_id` INT NOT NULL AUTO_INCREMENT,
  `ususkill_nivel` VARCHAR(45) NULL,
  `ususkill_veri` VARCHAR(1) NULL,
  `skill_id` INT NULL,
  `usu_id` INT NULL,
  PRIMARY KEY (`ususkill_id`),
  INDEX `fk_t_ususkill_t_skill1_idx` (`skill_id` ASC),
  INDEX `fk_t_ususkill_t_usuario1_idx` (`usu_id` ASC),
  CONSTRAINT `fk_t_ususkill_t_skill1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `codijob`.`t_skill` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_ususkill_t_usuario1`
    FOREIGN KEY (`usu_id`)
    REFERENCES `codijob`.`t_usuario` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codijob`.`t_proyectoimagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codijob`.`t_proyectoimagen` (
  `proimg_id` INT NOT NULL AUTO_INCREMENT,
  `proimg_url` TEXT NULL,
  `pro_id` INT NULL,
  PRIMARY KEY (`proimg_id`),
  INDEX `fk_t_proyectoimagen_t_proyecto1_idx` (`pro_id` ASC),
  CONSTRAINT `fk_t_proyectoimagen_t_proyecto1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `codijob`.`t_proyecto` (`pro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
